config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: redirect('yoga_poses')

  get 'yoga_poses', to: 'yoga_poses#index', as: 'yoga_poses'
  get 'yoga_poses/:id', to: 'yoga_poses#show', as: 'yoga_pose'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/yoga_pose.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: yoga_poses
#
#  id           :bigint           not null, primary key
#  name         :string
#  part_of_body :string
#  sanskrit     :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class YogaPose < ApplicationRecord
  validates :name, presence: true
  validates :part_of_body, inclusion: { in: %w[Legs Abs Arms Back Hamstrings Hips Chest Shoulders] }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/yoga_poses_controller.rb
# frozen_string_literal: true

class YogaPosesController < ApplicationController
  def index
    @yoga_poses = YogaPose.order(:name)
    render :index
  end

  def show
    @yoga_pose = YogaPose.find(params[:id])
    render :show
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  BOOTSTRAP_ALERT_CLASS = {
    'success' => 'alert-success',
    'error'   => 'alert-danger',
    'notice'  => 'alert-info',
    'alert'   => 'alert-danger',
    'warn'    => 'alert-warning'
  }.freeze

  def alert_class(flash_key)
    BOOTSTRAP_ALERT_CLASS.fetch(flash_key, 'alert-info')
  end
end

app/helpers/yoga_poses_helper.rb
# frozen_string_literal: true

module YogaPosesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YogaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/flash' %>

    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= alert_class(key) %> alert-dismissible fade show" role="alert">
    <div class="text-center alert-message"><%= message %></div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/yoga_poses/index.html.erb
<h1>Yoga Poses</h1>

<table class="table table-striped table-hover">

  <tbody>
    <% @yoga_poses.each do |p| %>
      <tr>
        <td><%= link_to p.name, yoga_pose_path(p) %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<p>
  <%= link_to 'New Pose', nil, class: 'btn btn-primary' %>
</p>

app/views/yoga_poses/show.html.erb
<h1><%= @yoga_pose.name %> Pose</h1>

<p>
  <i><%= @yoga_pose.sanskrit %></i>
</p>

<p>
  Part of Body: <%= @yoga_pose.part_of_body %>
</p>

<p>
  <%= link_to 'Back', yoga_poses_path, class: 'btn btn-secondary' %>
</p>